services:
  dragonfly:
    container_name: dragonfly
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly:v1.28.2'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./dragonflydata:/data
    command:
      [
        "--dir=/data",
        "--requirepass=${DRAGONFLY_PASSWORD}",
        "--bind=0.0.0.0"
      ]
    restart: always
  db:
    build:
      context: ./db
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pgnetwork
volumes:
  pgdata:
    driver: local
  pgadmin:
    driver: local
  dragonflydata:
    driver: local
networks:
  pgnetwork:
    driver: bridge

