[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.7", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
chrono = "0.4.40"
serde_json = "1.0.140"
