[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
log = "0.4.26"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.13.0", features=["macros"] }
tokio = { version = "1.43.0", features=["rt-multi-thread", "macros"] }
