[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
log = "0.4.25"
pretty_env_logger = "0.5.0"
serde = "1.0.217"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio-rustls"] }
teloxide = { version = "0.13.0", features = ["macros"] }
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
