[package]
name = "events"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version="0.30.0", features=["aio"] }
rust_decimal = "1.37.1"
serde = { version="1.0.219", features=["derive"] }
serde_json = "1.0.140"
